"""Adding subtitle

Revision ID: 3869e9f6ef49
Revises: dfa5d3aa3df3
Create Date: 2026-03-30 13:24:05.986236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3869e9f6ef49'
down_revision: Union[str, None] = 'dfa5d3aa3df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('subtitle', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_events_subtitle'), 'events', ['subtitle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_subtitle'), table_name='events')
    op.drop_column('events', 'subtitle')
    # ### end Alembic commands ###
