"""Update account_status enum to include pending_approval

Revision ID: 5c3a6f9b2d4e
Revises: 4b2f5e8a1c3d
Create Date: 2026-04-19 12:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3a6f9b2d4e'
down_revision: Union[str, None] = '4b2f5e8a1c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Change the enum to include pending_approval
    op.alter_column('users', 'account_status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', 'active', 'disabled', 'deleted'),
               type_=sa.Enum('pending', 'pending_approval', 'approved', 'rejected', 'active', 'disabled', 'deleted'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'account_status',
               existing_type=sa.Enum('pending', 'pending_approval', 'approved', 'rejected', 'active', 'disabled', 'deleted'),
               type_=sa.Enum('pending', 'approved', 'rejected', 'active', 'disabled', 'deleted'),
               existing_nullable=False)
    # ### end Alembic commands ###
