"""add Role,User,Organizer,Student tables

Revision ID: d00f8c05b7af
Revises: 03c300af080a
Create Date: 2026-04-08 21:36:11.022437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd00f8c05b7af'
down_revision: Union[str, None] = '03c300af080a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('account_status', sa.Enum('pending', 'approved', 'rejected', 'active', 'disabled', 'deleted'), nullable=False),
    sa.Column('permanent_qr_token', mysql.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(email Like '%%@student.birzeit.edu' OR email LIKE '%%@staff.birzeit.edu')", name='chk_users_email'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('permanent_qr_token')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    
    op.create_table('organizer_profiles',
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('club_name', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('organizer_id'),
    sa.UniqueConstraint('club_name')
    )
    op.create_table('student_profiles',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.String(length=20), nullable=False),
    sa.Column('major', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('student_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profiles')
    op.drop_table('organizer_profiles')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
