"""Add capacity field

Revision ID: dfa5d3aa3df3
Revises: 1dbda4586cf0
Create Date: 2026-03-28 20:33:26.627941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa5d3aa3df3'
down_revision: Union[str, None] = '1dbda4586cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'capacity')
    # ### end Alembic commands ###
