"""i am not sure

Revision ID: e4e697fd7135
Revises: 4d1b8a9f22cc
Create Date: 2026-07-12 16:03:21.687891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4e697fd7135'
down_revision: Union[str, None] = '4d1b8a9f22cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'certificates' in inspector.get_table_names():
        op.drop_table('certificates')
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_feedbacks_registration_id'), 'feedbacks', ['registration_id'], unique=False)
    op.alter_column('student_profiles', 'student_number',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               nullable=False)
    op.drop_index('uq_users_email', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('uq_users_email', 'users', ['email'], unique=True)
    op.alter_column('student_profiles', 'student_number',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_feedbacks_registration_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.create_table('certificates',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registration_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organizer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('organizer_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('event_title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('issued_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='certificates_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.user_id'], name='certificates_ibfk_4', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name='certificates_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], name='certificates_ibfk_3', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_certificate_registration', 'certificates', ['registration_id'], unique=True)
    op.create_index('ix_certificates_student_id', 'certificates', ['student_id'], unique=False)
    op.create_index('ix_certificates_registration_id', 'certificates', ['registration_id'], unique=True)
    op.create_index('ix_certificates_organizer_id', 'certificates', ['organizer_id'], unique=False)
    op.create_index('ix_certificates_id', 'certificates', ['id'], unique=False)
    op.create_index('ix_certificates_event_id', 'certificates', ['event_id'], unique=False)
    # ### end Alembic commands ###
